<?php

return [

    'ERR_PAYLOAD_INVALID'=> 400,
    'STATUS_CHOPE_ERROR' => 500,
    'STATUS_SUCCESS' => 200,
    'STATUS_LOGIC_ERROR' => 400,
    'STATUS_UNAUTHORIZED' => 401,
    'STATUS_FORRBIDDEN' => 403,
    'STATUS_NOT_FOUND' => 404,
    'STATUS_INTERNAL_SERVER_ERROR' => 500
];