-- MySQL Script generated by MySQL Workbench
-- Sun Aug  6 07:41:00 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fcc_booking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fcc_booking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fcc_booking` DEFAULT CHARACTER SET utf8 ;
USE `fcc_booking` ;

-- -----------------------------------------------------
-- Table `fcc_booking`.`staffs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcc_booking`.`staffs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `account_name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(20) NULL,
  `role` ENUM('Admin', 'Staff', 'Waiter') NOT NULL COMMENT '0:admin, 1: staff, 2: Waiter',
  `profile_image` VARCHAR(255) NULL,
  `table_color` VARCHAR(255) NULL COMMENT '#FFEEBB',
  `token` VARCHAR(255) NULL,
  `reset_pwd_token` VARCHAR(255) NULL,
  `reset_pwd_issued_time` DATETIME NULL,
  `reset_pwd_limit` INT NULL,
  `is_enabled` TINYINT NULL DEFAULT 0 COMMENT '1: enable, 0: disable',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `account_name_UNIQUE` (`account_name` ASC));


-- -----------------------------------------------------
-- Table `fcc_booking`.`floor_packages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcc_booking`.`floor_packages` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `is_publish` TINYINT NOT NULL DEFAULT 0 COMMENT '1:publish, 0:draft',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcc_booking`.`shift_packages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcc_booking`.`shift_packages` (
  `id` INT(11) NOT NULL,
  `package_name` VARCHAR(255) NOT NULL,
  `is_publish` TINYINT NOT NULL DEFAULT 0 COMMENT '1: publish, 0: draft',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcc_booking`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcc_booking`.`bookings` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `booking_number` VARCHAR(255) NOT NULL COMMENT '000001',
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `hours` INT NOT NULL,
  `number_of_people` INT NOT NULL,
  `status` ENUM('Booked', 'Confirmed', 'PartiallySeated', 'Seated', 'NotArrivedYet', 'WaitingInBar', 'GotTheCheck') CHARACTER SET 'big5' NOT NULL COMMENT 'Booked\nConfirmed\nPartially seated\nSeated\nNot arrived yet\nWaiting in bar\nGot the check\nCompleted\nNo show\nCancel\nCancel & Refund',
  `guest_id` INT NULL DEFAULT 0 COMMENT '0: Walk-in guest',
  `shift_package_id` INT(11) NOT NULL,
  `shift_id` INT(11) NOT NULL,
  `floor_package_id` INT(11) NOT NULL,
  `assigned_tables` VARCHAR(255) NULL,
  `notes_by_guest` VARCHAR(1024) NULL,
  `notes_by_staff` VARCHAR(1024) NULL,
  `expense` VARCHAR(255) NULL,
  `referenced_by` VARCHAR(225) NULL,
  `deposit_amount` FLOAT NULL,
  `deposit_method` ENUM('wxpay', 'alipay') NULL,
  `deposit_transaction_id` VARCHAR(255) NULL,
  `refund_error` VARCHAR(255) NULL,
  `refund_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_bookings_floor_packages1_idx` (`floor_package_id` ASC),
  INDEX `fk_bookings_shift_packages1_idx` (`shift_package_id` ASC),
  CONSTRAINT `fk_bookings_floor_packages1`
    FOREIGN KEY (`floor_package_id`)
    REFERENCES `fcc_booking`.`floor_packages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_shift_packages1`
    FOREIGN KEY (`shift_package_id`)
    REFERENCES `fcc_booking`.`shift_packages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcc_booking`.`floors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcc_booking`.`floors` (
  `id` INT(11) NOT NULL,
  `number` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcc_booking`.`tables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcc_booking`.`tables` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `table_number` INT NOT NULL,
  `table_name` VARCHAR(255) NULL,
  `seats` INT NOT NULL,
  `seat_from` INT NOT NULL,
  `seat_to` INT NOT NULL,
  `style` INT NOT NULL COMMENT '0:Rectangle\n1:Circle',
  `floor_id` INT(11) NOT NULL,
  `floor_package_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `non_reservable` TINYINT(1) NOT NULL DEFAULT 0,
  `table_layout` TEXT NULL COMMENT 'json string',
  PRIMARY KEY (`id`),
  INDEX `fk_tables_floors1_idx` (`floor_id` ASC),
  INDEX `fk_tables_floor_packages1_idx` (`floor_package_id` ASC),
  CONSTRAINT `fk_tables_floors1`
    FOREIGN KEY (`floor_id`)
    REFERENCES `fcc_booking`.`floors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tables_floor_packages1`
    FOREIGN KEY (`floor_package_id`)
    REFERENCES `fcc_booking`.`floor_packages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcc_booking`.`shifts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcc_booking`.`shifts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `time_slots` TEXT NOT NULL COMMENT 'JSON data({from:to},{from:to}...)',
  `floor_package_id` INT(11) NOT NULL DEFAULT 0 COMMENT '0: default package',
  `shift_package_id` INT(11) NOT NULL,
  `shfit_atb` INT NOT NULL DEFAULT 1 COMMENT 'hours(unit)',
  `deposit_amount` FLOAT NULL,
  `is_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '1: enable, 0: disable',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_shift_floor_packages1_idx` (`floor_package_id` ASC),
  INDEX `fk_shifts_shift_packages1_idx` (`shift_package_id` ASC),
  CONSTRAINT `fk_shift_floor_packages1`
    FOREIGN KEY (`floor_package_id`)
    REFERENCES `fcc_booking`.`floor_packages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shifts_shift_packages1`
    FOREIGN KEY (`shift_package_id`)
    REFERENCES `fcc_booking`.`shift_packages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcc_booking`.`rules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcc_booking`.`rules` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `repeat` INT NULL COMMENT '0: Every day\n1: Every week\n2: Every month\n3: Every Year',
  `repeat_end` DATETIME NULL,
  `shift_package_id` INT(11) NOT NULL DEFAULT 0 COMMENT '0: closed date',
  `color` VARCHAR(255) NULL COMMENT '#FFEEBB',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_rule_shift_packages1_idx` (`shift_package_id` ASC),
  CONSTRAINT `fk_rule_shift_packages1`
    FOREIGN KEY (`shift_package_id`)
    REFERENCES `fcc_booking`.`shift_packages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcc_booking`.`guests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcc_booking`.`guests` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `wechat_account` VARCHAR(255) NULL,
  `alipay_accoun_id` VARCHAR(255) NULL,
  `alipay_account_name` VARCHAR(255) NULL,
  `company_name` VARCHAR(255) NULL,
  `is_del` TINYINT NOT NULL DEFAULT 0 COMMENT '1: deleted',
  `is_block` TINYINT NOT NULL DEFAULT 0 COMMENT '1: blocked',
  `is_vip` TINYINT NOT NULL DEFAULT 0 COMMENT '1: vip',
  `sms_code` VARCHAR(255) NULL,
  `sms_send_time` DATETIME NULL,
  `sms_validation_time_limit` INT NULL,
  `sms_validation_count_limit` INT NULL,
  `token` VARCHAR(255) NULL,
  `token_issued_at` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcc_booking`.`staff_tables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcc_booking`.`staff_tables` (
  `staff_id` INT(11) NOT NULL,
  `table_id` INT(11) NOT NULL,
  `apply_date` DATETIME NOT NULL,
  `shift_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`staff_id`, `table_id`),
  INDEX `fk_staff_table_tables1_idx` (`table_id` ASC),
  INDEX `fk_staff_tables_shifts1_idx` (`shift_id` ASC),
  CONSTRAINT `fk_staff_table_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `fcc_booking`.`staffs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff_table_tables1`
    FOREIGN KEY (`table_id`)
    REFERENCES `fcc_booking`.`tables` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff_tables_shifts1`
    FOREIGN KEY (`shift_id`)
    REFERENCES `fcc_booking`.`shifts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcc_booking`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcc_booking`.`settings` (
  `id` INT(11) NOT NULL,
  `key` VARCHAR(255) NOT NULL COMMENT ' DEF_SHIFT_PKG_ID, DEF_FLOOR_PKG_ID, BOOKING_APP_TIMER...',
  `value` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcc_booking`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcc_booking`.`notifications` (
  `id` INT(11) NOT NULL,
  `type` ENUM('BookingCreated', 'BookingChanged', 'BookingDeleted', 'GuestCreated', 'GuestChanged', 'GuestDeleted', 'StaffCreated', 'StaffChanged', 'StaffDeleted') NOT NULL,
  `staff_id` INT(11) NOT NULL,
  `key_info1` VARCHAR(255) NULL COMMENT 'if type = \'booking create\',  booking_id\nif tyep = \'staff create\' ,staff_id\n',
  `key_info2` VARCHAR(255) NULL COMMENT 'if type = \'booking create\',  booking_date\nif tyep = \'staff create\' registered_date&time',
  `key_info3` VARCHAR(255) NULL COMMENT 'guest_id',
  `key_info4` VARCHAR(255) NULL,
  `key_info5` VARCHAR(255) NULL,
  `is_read` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcc_booking`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcc_booking`.`permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcc_booking`.`staff_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcc_booking`.`staff_permissions` (
  `id` INT(11) NOT NULL,
  `staff_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  `is_write` TINYINT NULL,
  `is_readonly` TINYINT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_staff_staff_permissions_staffs1_idx` (`staff_id` ASC),
  INDEX `fk_staff_staff_permissions_staff_permissions1_idx` (`permission_id` ASC),
  CONSTRAINT `fk_staff_staff_permissions_staffs1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `fcc_booking`.`staffs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff_staff_permissions_staff_permissions1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `fcc_booking`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcc_booking`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcc_booking`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `icon_image` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcc_booking`.`guest_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcc_booking`.`guest_tags` (
  `id` INT(11) NOT NULL,
  `guest_id` INT(11) NOT NULL,
  `tag_name` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tag_name_UNIQUE` (`tag_name` ASC),
  UNIQUE INDEX `guest_id_UNIQUE` (`guest_id` ASC),
  CONSTRAINT `fk_guest_tags_guests1`
    FOREIGN KEY (`guest_id`)
    REFERENCES `fcc_booking`.`guests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_guest_tags_tags1`
    FOREIGN KEY (`tag_name`)
    REFERENCES `fcc_booking`.`tags` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcc_booking`.`block_tables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcc_booking`.`block_tables` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `table_id` INT NOT NULL,
  `block_date` DATETIME NOT NULL,
  `is_allday` TINYINT NOT NULL DEFAULT 0 COMMENT '1: all day, 0: time range',
  `time_range_from` TIME NULL,
  `time_range_to` TIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_block_tables_tables1_idx` (`table_id` ASC),
  CONSTRAINT `fk_block_tables_tables1`
    FOREIGN KEY (`table_id`)
    REFERENCES `fcc_booking`.`tables` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcc_booking`.`assigned_tables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcc_booking`.`assigned_tables` (
  `table_id` INT(11) NOT NULL,
  `booking_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`table_id`, `booking_id`),
  CONSTRAINT `fk_assigned_tables_tables1`
    FOREIGN KEY (`table_id`)
    REFERENCES `fcc_booking`.`tables` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assigned_tables_bookings2`
    FOREIGN KEY (`booking_id`)
    REFERENCES `fcc_booking`.`bookings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
